In [1]:
import numpy as np

In [2]:
array_eye=np.eye(4)

array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
array_eye=np.eye(2)

array_eye

array([[1., 0.],
       [0., 1.]])

In [4]:
array_of_numbers=np.arange(1,20)

array_of_numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [5]:
array_of_evens=np.arange(2,30,2)

array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [9]:
array_of_odds=np.arange(1,30,2)

array_of_odds

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [10]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [11]:
x=np.arange(7)

x

array([0, 1, 2, 3, 4, 5, 6])

In [12]:
x.shape

(7,)

In [13]:
x=np.arange(7).reshape(1,7)

x

array([[0, 1, 2, 3, 4, 5, 6]])

In [14]:
x.shape

(1, 7)

In [15]:
y=np.arange(8).reshape(4,2)

y

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [16]:
y.shape

(4, 2)

In [17]:
z=np.arange(12).reshape(2,3,2)

z

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [18]:
z.shape

(2, 3, 2)

In [19]:
w=np.arange(16).reshape(2,2,2,2)

w

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [20]:
w.shape

(2, 2, 2, 2)