In [4]:
#Arrays

In [5]:
import numpy as np

In [7]:
array_one=np.array([1,2,3,4])

array_one

array([1, 2, 3, 4])

In [9]:
type(array_one)

numpy.ndarray

In [10]:
datatyp=np.array([6,7])

datatyp

array([6, 7])

In [12]:
numbers=[7,8,9]

array_two=np.array(numbers)

array_two

array([7, 8, 9])

In [14]:
array_of_zeros=np.zeros((3,4))

array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
array_of_ones=np.ones((2,3))

array_of_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
array_of_ones_int=np.ones((3,4),dtype=np.int16)

array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)